package psyknz.libgdx.games;

/* The ElementListener interface is for use with GameElements which generate events. The events generated by those GameElements are
 * passed to an ElementListener's event function so that the listener can process the event. */
public interface ElementListener {
    
	public void event(ElementEvent event);
}
